receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
  jaeger:
    endpoint: "http://jaeger:14250"
    tls:
      insecure: true
  otlp:
    endpoint: "logstash:5044"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, jaeger, otlp]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp]
